name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-head:
    runs-on: ubicloud-standard-8
    steps:
      - uses: actions/checkout@v4
      - uses: diodeinc/pcb-action/setup@v2
        with:
          version: HEAD
      - name: Build .zen files
        run: pcb build . -Dwarnings -S"deprecated.kicad"
      - name: Check formatting
        run: pcb fmt . --check

  test-latest:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubicloud-standard-8, macos-15-xlarge, diode-windows]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: diodeinc/pcb-action/setup@v2
        with:
          version: latest
      - name: Build .zen files
        run: pcb build . -Dwarnings -S"deprecated.kicad"
