name: Notify pcb repo

on:
  push:
    tags:
      - '*'

jobs:
  dispatch:
    runs-on: ubicloud-standard-4
    steps:
      - name: Trigger pcb stdlib version check
        env:
          GH_TOKEN: ${{ secrets.DIODE_ROBOT_TOKEN }}
        run: gh workflow run stdlib-version-check.yml --repo diodeinc/pcb
